[package]
name = "mini-assets"
version = "0.1.0-dev"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mini_assets"
path = "src/lib.rs"

[[bin]]
name = "mini-assets-gen"
path = "src/bin/gen.rs"

[dependencies]
